name: emb3rs-teo-module
channels:
  - defaults
dependencies:
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openpyxl=3.0.7
  - pandas=1.3.0
  - pickleshare=0.7.5
  - pip=21.1.3
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pygments=2.9.0
  - python=3.9.5
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pyzmq=20.0.0
  - setuptools=52.0.0
  - wheel=0.36.2
  - xlrd=2.0.1
  - pyscipopt=4.2.0
  - pip:
    - amply==0.1.4
    - docutils==0.17.1
#    - pulp==2.6.0
    - git+https://github.com/coin-or/pulp
    - pyparsing==2.4.7
    - Jinja2==3.0.3
    - json5==0.9.6
    - gurobipy==9.5.1
    - pydantic==1.9.0
    - highspy