name: emb3rs-teo-module
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - colorama=0.4.4
  - decorator=5.0.9
  - et_xmlfile=1.1.0
  - intel-openmp=2021.3.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jdcal=1.4.1
  - jedi=0.17.2
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openpyxl=3.0.7
  - openssl=1.1.1l
  - pandas=1.3.0
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.1.3
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pygments=2.9.0
  - python=3.9.5
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pyzmq=20.0.0
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xlrd=2.0.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
    - amply==0.1.4
    - docutils==0.17.1
    - pulp==2.4
    - pyparsing==2.4.7
